#Gradle
org.gradle.jvmargs=-Xmx8G
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.daemon=true
org.gradle.parallel=true

#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx4G
kotlin.mpp.enableCInteropCommonization=true
kotlin.native.ignoreDisabledTargets=true

#Android
android.useAndroidX=true
android.nonTransitiveRClass=true

#Project
app.version=4.4.4
app.code=54
app.desugar=false
app.proguard=false
database.version=12

android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.newDsl=false
