[versions]
adaptive = "1.2.0"
adaptive-suite = "1.9.0"
agp = "8.13.2"
androidx-activityCompose = "1.13.0"
androidx-lifecycle = "2.10.0"
androidx-navigation = "2.9.2"
androidx-uiTest = "1.11.2"
buildConfig = "6.0.10"
coil = "3.5.0"
compose = "1.10.3"
composeDnd = "0.4.0"
composePlaceholderMaterial3 = "1.0.12"
cryptographyCore = "0.6.0"
desugar_jdk_libs = "2.1.5"
filekitCore = "0.14.1"
glance = "1.1.1"
kermit = "2.1.0"
kolorPicker = "2.1.0"
koogAgents = "1.0.0"
kotlin = "2.4.0"
kotlinx-coroutines = "1.11.0"
kotlinx-datetime = "0.8.0"
kotlinx-serialization = "1.11.0"
ksoup = "0.2.6"
ksp = "2.3.8"
ktor = "3.5.0"
markdown = "0.41.0"
materialIconsExtended = "1.7.3"
materialKolor = "4.1.1"
mkmb-core = "1.3.0"
mkmb-platform = "1.3.0"
okio = "3.17.0"
orbitViewmodel = "11.0.0"
paging = "3.5.0"
reveal = "4.2.0"
room = "3.0.0-alpha06"
sonner = "0.3.9"
sqliteBundled = "2.6.2"
sweet = "0.1.3"
versionCatalogUpdate = "1.1.0"
workRuntimeKtx = "2.11.2"

[libraries]
adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "adaptive" }
adaptive-navigation-suite = { module = "org.jetbrains.compose.material3:material3-adaptive-navigation-suite", version.ref = "adaptive-suite" }
android-application-gradle-plugin = { module = "com.android.application:com.android.application.gradle.plugin", version.ref = "agp" }
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
android-library-gradle-plugin = { module = "com.android.library:com.android.library.gradle.plugin", version.ref = "agp" }
androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "glance" }
androidx-glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "glance" }
androidx-lifecycle-runtime = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-paging = { module = "androidx.paging:paging-common", version.ref = "paging" }
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqliteBundled" }
androidx-uitest-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx-uiTest" }
androidx-uitest-testManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-uiTest" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
coil = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
compose-dnd = { module = "com.mohamedrejeb.dnd:compose-dnd", version.ref = "composeDnd" }
compose-multiplatfrom-gradle-plugin = { module = "org.jetbrains.compose:org.jetbrains.compose.gradle.plugin", version.ref = "compose" }
compose-placeholder-material3 = { module = "com.eygraber:compose-placeholder-material3", version.ref = "composePlaceholderMaterial3" }
cryptography-core = { module = "dev.whyoleg.cryptography:cryptography-core", version.ref = "cryptographyCore" }
cryptography-provider-optimal = { module = "dev.whyoleg.cryptography:cryptography-provider-optimal", version.ref = "cryptographyCore" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
filekit-dialog = { module = "io.github.vinceglb:filekit-dialogs", version.ref = "filekitCore" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
kolor-picker = { module = "com.kborowy:kolor-picker", version.ref = "kolorPicker" }
koog-agents = { module = "ai.koog:koog-agents", version.ref = "koogAgents" }
kotlin-compose-compiler-gradle-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ksoup = { module = "com.fleeksoft.ksoup:ksoup", version.ref = "ksoup" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "adaptive-suite" }
materialKolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
mkmb-core = { module = "top.kagg886.mkmb:core", version.ref = "mkmb-core" }
mkmb-platform-linux = { module = "top.kagg886.mkmb:platform-linux", version.ref = "mkmb-platform" }
mkmb-platform-macos = { module = "top.kagg886.mkmb:platform-macos", version.ref = "mkmb-platform" }
mkmb-platform-windows = { module = "top.kagg886.mkmb:platform-windows", version.ref = "mkmb-platform" }
multiplatform-markdown-renderer-coil3 = { module = "com.mikepenz:multiplatform-markdown-renderer-coil3", version.ref = "markdown" }
multiplatform-markdown-renderer-m3 = { module = "com.mikepenz:multiplatform-markdown-renderer-m3", version.ref = "markdown" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
orbit-compose = { module = "org.orbit-mvi:orbit-compose", version.ref = "orbitViewmodel" }
orbit-core = { module = "org.orbit-mvi:orbit-core", version.ref = "orbitViewmodel" }
orbit-viewmodel = { module = "org.orbit-mvi:orbit-viewmodel", version.ref = "orbitViewmodel" }
reveal-core = { module = "com.svenjacobs.reveal:reveal-core", version.ref = "reveal" }
reveal-shapes = { module = "com.svenjacobs.reveal:reveal-shapes", version.ref = "reveal" }
room-compiler = { module = "androidx.room3:room3-compiler", version.ref = "room" }
room-paging = { module = "androidx.room3:room3-paging", version.ref = "room" }
room-runtime = { module = "androidx.room3:room3-runtime", version.ref = "room" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
sonner = { module = "io.github.dokar3:sonner", version.ref = "sonner" }
sweet-api-runtime = { module = "dev.whyoleg.sweetspi:sweetspi-runtime", version.ref = "sweet" }
sweet-compiler = { module = "dev.whyoleg.sweetspi:sweetspi-processor", version.ref = "sweet" }
compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-ui-test = { module = "org.jetbrains.compose.ui:ui-test", version.ref = "compose" }
compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose" }

[plugins]
benmanes-versions = "com.github.ben-manes.versions:0.54.0"
buildConfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildConfig" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room3", version.ref = "room" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "versionCatalogUpdate" }
