package top.kagg886.build

import javax.inject.Inject
import org.gradle.api.DefaultTask
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.model.ObjectFactory
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import org.gradle.kotlin.dsl.create

abstract class IosXcconfigExtension @Inject constructor(objects: ObjectFactory) {
    val outputFile: RegularFileProperty = objects.fileProperty()
}

class IosXcconfigPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        project.extensions.create<IosXcconfigExtension>("iosXcconfig").outputFile.convention(
            project.rootProject.layout.projectDirectory.file("iosApp/Generated.xcconfig"),
        )
    }
}

@CacheableTask
abstract class GenerateIosXcconfigTask : DefaultTask() {
    @get:Input
    abstract val marketingVersion: Property<String>

    @get:Input
    abstract val currentProjectVersion: Property<Int>

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun generate() {
        val file = outputFile.get().asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            // Generated by :composeApp:generateIosAppXcconfig. Do not edit manually.
            MARKETING_VERSION = ${marketingVersion.get()}
            CURRENT_PROJECT_VERSION = ${currentProjectVersion.get()}
            """.trimIndent() + "\n",
        )
        logger.lifecycle("Generated iOS xcconfig: ${file.absolutePath}")
    }
}
